<a href="https://colab.research.google.com/github/Mohit-Jangid/Numpy/blob/main/NumPy_for_Machine_Learning_Part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![](https://apmonitor.com/pds/uploads/Main/python_numpy.png)

<div style="color:white;
           display:fill;
           border-radius:5px;
           background-color:#5642C5;
           font-size:33px;
           font-family:Nexa;
           letter-spacing:0.5px">
        <p style="padding: 15px;
              color:white;">
            <b>What is numpy?</b>
        </p>
</div>

<blockquote style="margin-right:auto; margin-left:auto; background-color: #FAFAD2; padding: 1em; margin:2px;font-size:18px;font-family:Comic Sans Ms;color:#660000;letter-spacing:0.7px;text-align: justify;">

NumPy is a Python library that provides powerful and versatile array computations, mathematical functions, and other tools for various scientific domains. It is widely used in data science, machine learning, and scientific computing. NumPy offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.

<font color="Blue" size=+2 face="Times New Roman"><div style="text-align: Left">Numpy Vs Pandas</font>

<blockquote style="margin-right:auto; margin-left:auto; background-color: #FAFAD2; padding: 1em; margin:3px;font-size:25px;font-family:Comic Sans Ms;color:#660000;letter-spacing:0.7px;text-align: justify;">


| NumPy | Pandas |
|------------|-----------|
| Provides powerful and versatile array computations, mathematical functions, and other tools for various scientific domains          | Built on top of NumPy and provides high-performance, fast, easy-to-use data structures, and data analysis tools for manipulating numeric data and time series.      |
| Offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.          | Offers powerful data analysis tools like DataFrame and Series, which provide rich time series functionality, data alignment, NA-friendly statistics, groupby, merge and join methods, and lots of other conveniences      |
|Provides high-performance multidimensional arrays and tools to deal with them           |  Consumes more memory than NumPy but is more memory-efficient than other Python data analysis libraries.      |
| Is used to perform scientific computing          | Is used for data manipulation and analysis    |

# Creating Numpy Arrays

In [1]:
# np.array
import numpy as np

# create numpy 1D array
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [2]:
# type of array
print(type(a))

<class 'numpy.ndarray'>


In [3]:
#1D array of length 10 all values 0
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
#5x5 array with all values 1
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
#5x5 array of 0 with 1 on diagonal Identitymatrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
#create 2D array
b = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [7]:
# create 3D array
c = np.array([[[1, 2, 3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [8]:
#here 1,15 is the range means give me 3 numbers having values between 1-15
np.random.randint(1,15,3)

array([12,  9, 12])

In [9]:
#3x3 array with random ints between 0–9
np.random.randint(10,size=(3,3))

array([[7, 4, 9],
       [6, 6, 6],
       [9, 3, 6]])

In [10]:
# bool datatype
np.array([1, 2, 3, 4, 5], dtype=bool)

array([ True,  True,  True,  True,  True])

In [11]:
#7x7 array of 0 with 1 on diagonal Identitymatrix
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [12]:
#Array of values from 0 to less than 15 with step 3
np.arange(0,15,3)

array([ 0,  3,  6,  9, 12])

In [13]:
from numpy import *
a = arange(12)
a = a.reshape(3,2,2)
print(a)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [14]:
#Transposes arr (rows become columns and vice versa)
trans=np.array([(1,2,3,4),(5,6,7,8)])
trans.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [15]:
trans.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [16]:
#Changes arr shape to 6x6 and fills new values with 0
trans.resize((6,6),refcheck=False)
trans

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [17]:
#Returns number of elements in arr
arr=np.array([1,2,3,4,6,7,9])
arr.size

7

In [18]:
#Appends values to end of arr
arr2=np.append(arr,[0,1,2,4,5])
arr2

array([1, 2, 3, 4, 6, 7, 9, 0, 1, 2, 4, 5])

In [19]:
#Inserts values into arr before index 2
np.insert(arr2,2,4)

array([1, 2, 4, 3, 4, 6, 7, 9, 0, 1, 2, 4, 5])

In [20]:
#Deletes row on index 4 of arr
np.delete(trans,4)

array([1, 2, 3, 4, 6, 7, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
#Deletes column on index 5 of arr
np.delete(trans,5,axis=1)

array([[1, 2, 3, 4, 5],
       [7, 8, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [22]:
abs(-1)

1

In [23]:
add.accumulate(array([1.,2.,3.,4.]))

array([ 1.,  3.,  6., 10.])

In [24]:
multiply.accumulate(array([1.,2.,3.,4.]))

array([ 1.,  2.,  6., 24.])

In [25]:
add.accumulate(array([[1,2,3],[4,5,6]]), axis = 0)

array([[1, 2, 3],
       [5, 7, 9]])

In [26]:
add.accumulate(array([[1,2,3],[4,5,6]]), axis = 1)

array([[ 1,  3,  6],
       [ 4,  9, 15]])

In [27]:
add(array([-1.2, 1.2]), array([1,3]))

array([-0.2,  4.2])

In [28]:
array([-1.2, 1.2]) + array([1,3])

array([-0.2,  4.2])

In [29]:
a = array([True, False, True])
a.all()

False

In [30]:
allclose(array([1e10,1e-7]), array([1.00001e10,1e-8]))

False

In [31]:
# in radians
angle(1+1j)

0.7853981633974483

In [32]:
# in degrees
angle(1+1j,deg=True)

45.0

In [33]:
# gives True if at least 1 element of a is True, otherwise False
a = array([True, False, True])
a.any()

True

In [34]:
from numpy import *
a = array([10,20,30,40])
append(a,50)

array([10, 20, 30, 40, 50])

In [35]:
array([10, 20, 30, 40, 50])
append(a,[50,60])

array([10, 20, 30, 40, 50, 60])

In [36]:
array([10, 20, 30, 40, 50])
append(a,[59,60])

array([10, 20, 30, 40, 59, 60])

In [37]:
#View documentation for arr.tolist
np.info(arr.tolist)

a.tolist()

Return the array as an ``a.ndim``-levels deep nested list of Python scalars.

Return a copy of the array data as a (nested) Python list.
Data items are converted to the nearest compatible builtin Python type, via
the `~numpy.ndarray.item` function.

If ``a.ndim`` is 0, then since the depth of the nested list is 0, it will
not be a list at all, but a simple Python scalar.

Parameters
----------
none

Returns
-------
y : object, or list of object, or list of list of object, or ...
    The possibly nested list of array elements.

Notes
-----
The array may be recreated via ``a = np.array(a.tolist())``, although this
may sometimes lose precision.

Examples
--------
For a 1D array, ``a.tolist()`` is almost the same as ``list(a)``,
except that ``tolist`` changes numpy scalars to Python scalars:

>>> a = np.uint32([1, 2])
>>> a_list = list(a)
>>> a_list
[1, 2]
>>> type(a_list[0])
<class 'numpy.uint32'>
>>> a_tolist = a.tolist()
>>> a_tolist
[1, 2]
>>> type(a_tolist[0])
<class 'int'

In [38]:
from numpy import *
def myfunc(a): # function works on a 1d arrays, takes the average of the 1st an last element
    return (a[0]+a[-1])/2
b = array([[1,2,3],[4,5,6],[7,8,9]])
apply_along_axis(myfunc,0,b)

array([4., 5., 6.])

In [39]:
from numpy import *
a = arange(24).reshape(2,3,4) # a has 3 axes: 0,1 and 2
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [40]:
# sum over all axes except axis=1, result has same shape as original
apply_over_axes(sum, a, [0,2])

array([[[ 60],
        [ 92],
        [124]]])

In [41]:
from numpy import *
arange(5)

array([0, 1, 2, 3, 4])

In [42]:
arange(5.0)

array([0., 1., 2., 3., 4.])

In [43]:
from numpy import *
arccos(array([0, 1]))

array([1.57079633, 0.        ])

In [44]:
arccosh(array([e, 10.0]))

array([1.65745445, 2.99322285])

In [ ]:
arcsin(array([0, 1]))

In [ ]:
arcsinh(array([e, 10.0]))

In [ ]:
arctan(array([0, 1]))

In [ ]:
arctan2(array([0, 1]), array([1, 0]))

In [ ]:
arctanh(array([0, -0.5]))

In [45]:
from numpy import *
a = array([10,20,30])
maxindex = a.argmax()
a[maxindex]

30

In [46]:
a = array([[10,50,30],[60,20,40]])
maxindex = a.argmax()
maxindex

3

In [47]:
a.ravel()[maxindex]

60

In [48]:
# for each column: the row index of the maximum value
a.argmax(axis=0)

array([1, 0, 1])

In [49]:
# for each row: the column index of the maximum value
a.argmax(axis=1)

array([1, 0])

In [50]:
# also exists, slower, default is axis=-1
argmin(a)

0

In [51]:
from numpy import *
a = array([2,0,8,4,1])
a

array([2, 0, 8, 4, 1])

In [ ]:
# indices of sorted array using quicksort (default)
ind = a.argsort()
ind

In [ ]:
# same effect as a.sort()
a[ind]

In [ ]:
ind = a.argsort(kind='merge') # algorithm options are 'quicksort', 'mergesort' and 'heapsort'
a = array([[8,4,1],[2,0,9]])
ind = a.argsort(axis=0) # sorts on columns. NOT the same as a.sort(axis=1)
ind

In [ ]:
from numpy import *
abs(-1)

In [ ]:
abs(array([-1.2, 1.2]))

In [ ]:
abs(1.2+1j)

In [ ]:
# like reduce() but also gives intermediate results
from numpy import *
add.accumulate(array([1.,2.,3.,4.]))

In [ ]:
# works also with other operands
multiply.accumulate(array([1.,2.,3.,4.]))

In [ ]:
#Array of 5 evenly divided values from 0 to 150
np.linspace(0,150,5)

In [ ]:
#Returns number of elements in arr
arr=np.array([1,2,3,4,6,7,9])
arr.size

In [52]:
#Returns dimensions of arr (rows,columns)
arr.shape

(7,)

In [ ]:
#Convert arr to a Python list
arr.tolist()

In [ ]:
#Copies arr to new memory
np.copy(arr)

In [53]:
#Sorts arr
arr.sort()
arr

array([1, 2, 3, 4, 6, 7, 9])

In [54]:
#Sorts specific axis of arr
arr.sort(axis=0)
arr

array([1, 2, 3, 4, 6, 7, 9])

In [55]:
#Appends values to end of arr
arr2=np.append(arr,[0,1,2,4,5])
arr2

array([1, 2, 3, 4, 6, 7, 9, 0, 1, 2, 4, 5])

In [ ]:
np.concatenate((arr,arr2),axis=0) #Adds arr2 as rows to the end of arr1

In [ ]:
#Adds arr2 as columns to end of arr1
trans=np.array([(1,2,3,4),(5,6,7,8)])
np.concatenate((trans,trans),axis=1)